// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.MockConfigTests.MockConfig_EnteringNewValidData_ReturnsFalse(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.MockConfigTests.MockConfig_EnteringNewValidData_ReturnsTrue(System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.MockConfigTests.MockConfig_SettingInvalidData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.FileConfig_ValidConstructor_ThrowsException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.GetConfigValue_NameMatchesValueInFile_ReturnsTrue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.GetConfigValue_NameDoesNotMatchValueInFile_ReturnsFalse")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.SetFileConfig_NameUpdatedWithNewValue_ReturnsTrue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.FileConfigTests.SetFileConfig_FileNotFound_ReturnsFalse")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.GetConfigValue_NameIsNull_ThrowsArgumentNullException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.GetConfigValue_NameIsValid_ReturnsTrue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.SetConfigValue_NameIsNull_ReturnsFalse")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Naming", "CA1707:Identifiers should not contain underscores", Justification = "Naming convention for Test Method is Valid", Scope = "member", Target = "~M:Configuration.Tests.EnvironmentConfigTests.SetConfigValue_NameIsValid_ReturnsTrue")]
